apiVersion: v1
data:
  airflow.cfg: "[celery]\nflower_url_prefix = \nworker_concurrency = 16\n\n[celery_kubernetes_executor]\nkubernetes_queue
    = kubernetes\n\n[core]\ncolored_console_log = False\ntest_connection = Enabled\ndags_folder = /opt/airflow/dags/repo/airflow/dags\nexecutor
    = CeleryExecutor\nload_examples = False\nremote_logging = False\n\n[elasticsearch]\njson_format
    = True\nlog_id_template = {dag_id}_{task_id}_{execution_date}_{try_number}\n\n[elasticsearch_configs]\nmax_retries
    = 3\nretry_timeout = True\ntimeout = 30\n\n[kerberos]\nccache = /var/kerberos-ccache/cache\nkeytab
    = /etc/airflow.keytab\nprincipal = airflow@FOO.COM\nreinit_frequency = 3600\n\n[kubernetes]\nairflow_configmap
    = airflow-config\nairflow_local_settings_configmap = airflow-config\nmulti_namespace_mode
    = False\nnamespace = airflow\npod_template_file = /opt/airflow/pod_templates/pod_template_file.yaml\nworker_container_repository
    = projonas/airflow-custom\nworker_container_tag = 1.0.0\n\n[kubernetes_executor]\nmulti_namespace_mode
    = False\nnamespace = airflow\npod_template_file = /opt/airflow/pod_templates/pod_template_file.yaml\nworker_container_repository
    = projonas/airflow-custom\nworker_container_tag = 1.0.0\n\n[logging]\ncolored_console_log
    = False\nremote_logging = False\n\n[metrics]\nstatsd_host = airflow-statsd\nstatsd_on
    = True\nstatsd_port = 9125\nstatsd_prefix = airflow\n\n[scheduler]\nrun_duration
    = 41460\nstandalone_dag_processor = False\nstatsd_host = airflow-statsd\nstatsd_on
    = True\nstatsd_port = 9125\nstatsd_prefix = airflow\n\n[triggerer]\ndefault_capacity
    = 1000\n\n[webserver]\nenable_proxy_fix = True\nexpose_config = True\nrbac = True"
  airflow_local_settings.py: |2-

    from airflow.www.utils import UIAlert

    DASHBOARD_UIALERTS = [
      UIAlert(
        'Usage of a dynamic webserver secret key detected. We recommend a static webserver secret key instead.'
        ' See the <a href='
        '"https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#webserver-secret-key">'
        'Helm Chart Production Guide</a> for more details.',
        category="warning",
        roles=["Admin"],
        html=True,
      )
    ]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  creationTimestamp: "2023-10-27T18:38:34Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.11.0
    component: config
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-config
  namespace: airflow
  resourceVersion: "455287"
  uid: 856bfbcb-4c9b-4e89-a629-2ebf210afcdb
